name: Build Release with Installer

on:
  release:
    types: [created]

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Install WiX Toolset
      run: |
        $wixToolsetUrl = "https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314.exe"
        $wixToolsetInstaller = "$env:TEMP\wix314.exe"
        Invoke-WebRequest -Uri $wixToolsetUrl -OutFile $wixToolsetInstaller
        Start-Process -FilePath $wixToolsetInstaller -ArgumentList "/q" -Wait
        echo "C:\Program Files (x86)\WiX Toolset v3.14\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - name: Restore dependencies
      run: dotnet restore ./projects
    
    - name: Build
      run: dotnet build ./projects --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish ./projects -c Release -r win-x64 --self-contained
    
    - name: Build Installer
      run: .\build-installer.ps1
    
    - name: Create ZIP package of published files
      run: |
        New-Item -ItemType Directory -Path .\publish-zip -Force
        Compress-Archive -Path .\projects\chronWindowsImageResizer\bin\Release\net8.0\win-x64\publish\* -DestinationPath .\publish-zip\ChronoImageResizer.zip
    
    - name: Upload MSI to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./projects/ChronoImageResizer.Setup/bin/Release/ChronoImageResizer.msi
        asset_name: ChronoImageResizer.msi
        asset_content_type: application/octet-stream
    
    - name: Upload ZIP of Published Files
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./publish-zip/ChronoImageResizer.zip
        asset_name: ChronoImageResizer.zip
        asset_content_type: application/zip 